extends:
  - "@commitlint/config-lerna-scopes"
  - "@commitlint/config-conventional"
rules:
  subject-full-stop: [0, "never", "."]
  subject-case: [0, "always", "sentence-case"]
  header-full-stop: [0, "never", "."]
  header-max-length: [1, "always", 72]
  type-enum:
    - 2
    - always
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
help: |
  **Possible types**:
  `build`:            Change build process, tooling or dependencies.
  `chore`:            Updating grunt tasks etc.; no production code change.
  `ci`:               Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs).
  `docs`:             Adds or alters documentation.
  `feat`:             Adds a new feature.
  `fix`:              Solves a bug.
  `perf`:             Improves performance.
  `refactor`:         Rewrites code without feature, performance or bug changes.
  `revert`:           Changes that reverting other changes.
  `style`:            Improves formatting, white-space.
  `test`:             Adds or modifies tests.
