name: validate commits

on:
  workflow_call:

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    name: Enforce conventional commits
    steps:
      - name: Source checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify with commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ".github/configs/commitlintrc.yml"
