name: validate generic code

on:
  workflow_call:
    inputs:
      dockerlint:
        description: Run dockerlint
        required: false
        type: boolean
        default: false
      dockerfile:
        description: Dockerfile path for linting (default Dockerfile)
        required: false
        type: string
        default: Dockerfile
      markdownlint:
        description: Run Markdown lint
        required: false
        type: boolean
        default: false
      rustlint:
        description: Run rust lint
        required: false
        type: boolean
        default: false
      workflowlint:
        description: Run workflow lint
        required: false
        type: boolean
        default: false
      yamllint:
        description: Run yaml lint
        required: false
        type: boolean
        default: false
      debug:
        description: Enable debugging
        required: false
        type: boolean
        default: false
jobs:
  validate-code:
    name: Validate application, actions and docker code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

        with:
          fetch-depth: 0

      # Dockerfile
      - name: Lint Dockerfile
        if: ${{ inputs.dockerlint == true }}
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: ${{ inputs.dockerfile }}
          # dockerfile: ${{ format('{0}/{1}', github.workspace, inputs.dockerfile) }}

      # Markdown
      - name: Lint Markdown
        if: ${{ inputs.markdownlint }}
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .

      # Rust source
      - name: Lint Rust source - add clippy
        if: ${{ inputs.rustlint == true }}
        run: rustup component add clippy

      - name: lint Rust source
        if: ${{ inputs.rustlint == true }}
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      # Workflows
      - name: Lint workflows
        if: ${{ inputs.workflowlint == true }}
        uses: cfy9/action-linting@v0.0.1
        with:
          arguments: "-color"

      # Yaml
      - name: Lint yaml files
        if: ${{ inputs.yamllint == true }}
        uses: ibiqlik/action-yamllint@v3.1.1
