name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  validate-commits:
    uses: ./.github/workflows/validate-commits.yml

  lint:
    uses: ./.github/workflows/validate-code.yml
    with:
      workflowlint: true
