name: Validate

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  validate-commits:
    uses: ./.github/workflows/validate-commits.yml

  lint:
    uses: ./.github/workflows/validate-code.yml
    with:
      workflowlint: true
