name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  validate-commits:
    uses: oberiworks/workflows/.github/workflows/validate-commits.yml@main

  lint:
    uses: oberiworks/workflows/.github/workflows/validate-code.yml@main
    with:
      workflowlint: true
